 CREATE DATABASE EgitimPlatformu
 use EgitimPlatformu

CREATE TABLE Kullanici(
KullaniciID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY  NOT NULL,
Name NVARCHAR(25) NOT NULL,
Soyad NVARCHAR(25) NOT NULL,
Telefon BIGINT NOT NULL,
);

CREATE TABLE Mail(
KullaniciID UNIQUEIDENTIFIER NOT NULL,
Mail NVARCHAR(50) NOT NULL,
Sifre NVARCHAR(50) NOT NULL,
	FOREIGN KEY (KullaniciID) REFERENCES Kullanici(KullaniciID),
);

CREATE TABLE Paketler(
PaketID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY  NOT NULL,
PaketAdi NVARCHAR(7) NOT NULL,
PaektFiyati MONEY NOT NULL,
);

CREATE TABLE PaketBilgileri(
PaketID UNIQUEIDENTIFIER NOT NULL,
PaketOzellik1 NVARCHAR(20) NOT NULL,
PaketOzellik2 NVARCHAR(20) NOT NULL,
	FOREIGN KEY (PaketID) REFERENCES Paketler(PaketID),
);

CREATE TABLE Egitim(
EgitimID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY  NOT NULL,
EgitimAdi NVARCHAR(30) NOT NULL,
EgitimFiyati MONEY NOT NULL,
);

CREATE TABLE EgitimKonularý(
EgitimID UNIQUEIDENTIFIER NOT NULL,
DersIcerigi NVARCHAR(100) NOT NULL,
	FOREIGN KEY (EgitimID) REFERENCES Egitim(EgitimID),
);

CREATE TABLE Paketlerim(
KullaniciID UNIQUEIDENTIFIER NOT NULL,
PaketID UNIQUEIDENTIFIER NOT NULL,
BaslangicTarihi DATE DEFAULT GETDATE() NOT NULL
    FOREIGN KEY (KullaniciID) REFERENCES Kullanici(KullaniciID),
	FOREIGN KEY (PaketID) REFERENCES Paketler(PaketID),
);

CREATE TABLE Sepet(
SepetID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY  NOT NULL,
KullaniciID UNIQUEIDENTIFIER NOT NULL,
PaketID UNIQUEIDENTIFIER NOT NULL,
EgitimID UNIQUEIDENTIFIER NOT NULL,
SepetToplamFiyati MONEY NOT NULL,
	FOREIGN KEY (KullaniciID) REFERENCES Kullanici(KullaniciID),
	FOREIGN KEY (PaketID) REFERENCES Paketler(PaketID),
	FOREIGN KEY (EgitimID) REFERENCES Egitim(EgitimID),
);

CREATE TABLE Egitimlerim(
KullaniciID UNIQUEIDENTIFIER NOT NULL,
EgitimID UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (KullaniciID) REFERENCES Kullanici(KullaniciID),
	FOREIGN KEY (EgitimID) REFERENCES Egitim(EgitimID),
);




